import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import "./fontawesome";
const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["400", "500", "700"], // Choose the weights you need
  style: ["normal", "italic"], // Choose the styles you need
  subsets: ["latin"], // Choose the subsets you need
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        
      </head>
      <body className={"bg-black text-white font-san"}>{children}</body>
    </html>
  );
}
